import { HotelData } from './types';

const hotels: HotelData[] = [
  {
    id: 1,
    name: 'Diamond Heart Hotel',
    location: 'Austrian Alps',
    image: require('/Users/sky9two/Desktop/Project/HotelBooking/src/assets/images/diamondhotel.jpg'),
    rating: 4.6,
    reviewCount: 142,
    description:
      'Diamond Heart Hotel is high rated hotels in Middle Java Purwokerto with 120+ reviews and have high attitude service...',
    pricePerNight: 250,
    beds: 2,
    wifi: true,
    gym: true,
    breakfast: true,
  },
  {
    id: 2,
    name: 'Radisson Blue',
    location: 'Carpathian Mountains',
    image: require('/Users/sky9two/Desktop/Project/HotelBooking/src/assets/images/radisonblue.jpg'),
    rating: 4.3,
    reviewCount: 98,
    description:
      'Luxury in the heart of Carpathians with modern rooms and scenic views.',
    pricePerNight: 220,
    beds: 3,
    wifi: true,
    gym: true,
    breakfast: false,
  },
  {
    id: 3,
    name: 'Alpine Glow Lodge',
    location: 'Swiss Alps',
    image: require('/Users/sky9two/Desktop/Project/HotelBooking/src/assets/images/alpineglowlodge.webp'),
    rating: 4.8,
    reviewCount: 215,
    description:
      'Elegant alpine escape surrounded by pristine snow and warm service.',
    pricePerNight: 280,
  },
  {
    id: 4,
    name: 'Lakeview Apartment',
    location: 'Hallstatt Lake',
    image: require('/Users/sky9two/Desktop/Project/HotelBooking/src/assets/images/lakeviewappartment.jpg'),
    rating: 4.2,
    reviewCount: 65,
    description:
      'Cozy lakeside stay with picturesque views and private balconies.',
    pricePerNight: 180,
    beds: 1,
    wifi: true,
    gym: true,
    breakfast: true,
  },
  {
    id: 5,
    name: 'Ski Peak Resort',
    location: 'Aspen Mountains',
    image: require('/Users/sky9two/Desktop/Project/HotelBooking/src/assets/images/skipeak.webp'),
    rating: 4.7,
    reviewCount: 170,
    description:
      'A premium ski resort offering all-season adventure and luxury.',
    pricePerNight: 300,
    beds: 4,
    wifi: true,
    gym: true,
    breakfast: false,
  },
  {
    id: 6,
    name: 'Bukovel Grand Resort',
    location: 'Ukraine, Bukovel',
    image: require('/Users/sky9two/Desktop/Project/HotelBooking/src/assets/images/15315911-city-67244-1732c48864f.jpg'),
    rating: 4.5,
    reviewCount: 120,
    description:
      'Modern comfort in the heart of Bukovel ski valley with spa and sauna access.',
    pricePerNight: 210,
    beds: 2,
    wifi: true,
    gym: true,
    breakfast: true,
  },
  {
    id: 7,
    name: 'Snow Valley Inn',
    location: 'Ukraine, Bukovel',
    image: require('/Users/sky9two/Desktop/Project/HotelBooking/src/assets/images/01_B3GkJQ.jpg'),
    rating: 4.3,
    reviewCount: 88,
    description:
      'A peaceful mountain retreat perfect for couples and small families.',
    pricePerNight: 160,
    beds: 1,
    wifi: true,
    gym: true,
  },
  {
    id: 8,
    name: 'Bukovel Panorama Hotel',
    location: 'Ukraine, Bukovel',
    image: require('/Users/sky9two/Desktop/Project/HotelBooking/src/assets/images/260914782.jpg'),
    rating: 4.6,
    reviewCount: 130,
    description:
      'Stunning panoramic views of the Ukrainian Carpathians with cozy wood interiors.',
    pricePerNight: 240,
    beds: 3,
    wifi: true,
    gym: true,
    breakfast: false,
  },
];

export default hotels;
